twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'tailwind_2_layout.html.twig'
        - '_forms/layout.html.twig'
    paths:
      '%kernel.project_dir%/assets/styles': styles
      '%kernel.project_dir%/assets/images': images


    globals:
        app_locale: '%kernel.default_locale%'
        gmaps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
        stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
        cdn_host: '%cdn_host%'

when@test:
    twig:
        strict_variables: true
