doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            rental_status: string
            subscription_status: string
            booking_status: string
        types:
            bed_size: App\Infrastructure\Doctrine\Types\BedSizeType
            rental_status: App\Infrastructure\Doctrine\Types\RentalStatusType
            subscription_status: App\Infrastructure\Doctrine\Types\SubscriptionStatusType
            discount_type: App\Infrastructure\Doctrine\Types\DiscountTypeType
            price: App\Infrastructure\Doctrine\Types\PriceType
            booking_status: App\Infrastructure\Doctrine\Types\BookingStatusType
            booking_prices: App\Infrastructure\Doctrine\Types\BookingPricesType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
