<?php

namespace App\Doctrine\Types;

use App\Domain\Rental\Status;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\ORM\Exception\NotSupported;

final class RentalStatusType extends AbstractEnumType
{
    protected $name = 'rental_status';

    protected function getCases(): array
    {
        return Status::cases();
    }

    protected function tryFrom(string $value): mixed
    {
        $value = Status::tryFrom($value);
        if (null === $value) {
            throw new NotSupported('Status does not support '. $value .' value');
        }

        return $value;
    }

    public function getMappedDatabaseTypes(AbstractPlatform $platform)
    {
        return parent::getMappedDatabaseTypes($platform); // TODO: Change the autogenerated stub
    }


}