<?php

namespace App\Doctrine\Types;

use App\Domain\Subscription\SubscriptionStatus;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\ORM\Exception\NotSupported;

/**
 * @extends AbstractEnumType<SubscriptionStatus>
 */
final class SubscriptionStatusType extends AbstractEnumType
{
    protected string $name = 'subscription_status';

    protected function getCases(): array
    {
        return SubscriptionStatus::cases();
    }

    protected function tryFrom(string $value): mixed
    {
        $value = SubscriptionStatus::tryFrom($value);
        if (null === $value) {
            throw new NotSupported('Status does not support ' . $value . ' value');
        }

        return $value;
    }

    public function getMappedDatabaseTypes(AbstractPlatform $platform): array
    {
        return parent::getMappedDatabaseTypes($platform); // TODO: Change the autogenerated stub
    }
}
